---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[curl]
    - recipe[etcd::compile_time]
    - recipe[services_test::client]
    - recipe[services]
  attributes:
    etcd:
      upstart:
        start_on: 'runlevel [2345]'
        stop_on: 'runlevel [!2345]'
      servers:
        - 127.0.0.1

- name: blank
  run_list:
    - recupe[ubuntu]
    - recipe[etcd::compile_time]
    - recipe[services_test::blank]
    - recipe[services]
  attributes:
    etcd:
      servers:
        - 127.0.0.1
