---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config: 
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  run_list: recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box


suites:
- name: default
  run_list:
    - recipe[curl]
    - recipe[etcd::compile_time]
    - recipe[services_test::client]
    - recipe[services]
  attributes: 
    etcd:
      args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
      servers:
        - 127.0.0.1

clusters:
  default:
    - default
